### PR TITLE
Update Travis config for new Nextcloud versions (+ compatibility)

### PR DESCRIPTION
**Pull request by LEDfan**
New release => new tests :smiley: 

Currently Travis is failing because of some deprecated features used in NC 13:
```
The command "vendor/bin/php-cs-fixer fix --dry-run --using-cache=no" exited with 0.
2.27s$ rm -r build/ && rm -r vendor/ && ../../occ app:check-code ojsxc
Analysing /home/travis/build/nextcloud/nextcloud/apps/ojsxc/appinfo/app.php
 2 errors
    line    5: OCP\App - Static method of deprecated class must not be called
    line    5: OCP\App::registerPersonal - Method of deprecated class must not be called
Analysing /home/travis/build/nextcloud/nextcloud/apps/ojsxc/lib/Controller/SettingsController.php
 2 errors
    line  269: OCP\User - Static method of deprecated class must not be called
    line  269: OCP\User::isLoggedIn - Method of deprecated class must not be called
Analysing /home/travis/build/nextcloud/nextcloud/apps/ojsxc/settings/personal.php
 2 errors
    line    7: OCP\User - Static method of deprecated class must not be called
    line    7: OCP\User::checkLoggedIn - Method of deprecated class must not be called
App is not compliant
````

 - The first error can be solved by simple removing the line, but this will only work starting from NC 12 (tested in VM).
 - The second error is a simple replacement.
 - According to https://github.com/nextcloud/jsxc.nextcloud/blob/master/settings/personal.php#L4 the third error can be solved by removing the whole file but this is only NC 13 compatible. 

@sualko what do you think would be the best solution:
 - ignore the deprecation warnings (it are warnings after all)
 - fix the errors and only release new versions of the app for NC 13. 
   The #57 will only work with NC 13 (because of new API) but is made compatible with older versions.

### CODE REVIEW

**Comment by LEDfan** [comment]
Some more deprecated/compatibility  stuff which could be solved: 
 - [ ] https://github.com/nextcloud/jsxc.nextcloud/blob/4b6daef6b775e5372dce62ccaaba6faac3cff6c2/appinfo/application.php#L278 
 - [ ] https://github.com/nextcloud/jsxc.nextcloud/blob/4b6daef6b775e5372dce62ccaaba6faac3cff6c2/appinfo/application.php#L281
 - [ ] https://github.com/nextcloud/jsxc.nextcloud/blob/32bd542d4df06b8210c449f5c38653d39b5748ea/lib/Controller/SettingsController.php#L332
 - [ ] https://github.com/nextcloud/jsxc.nextcloud/blob/4e1922e1060f5d54c7ecc661aed121b9f94b15dd/lib/Settings/Section.php#L66
 - [ ] https://github.com/nextcloud/jsxc.nextcloud/blob/4e1922e1060f5d54c7ecc661aed121b9f94b15dd/lib/Settings/Section.php#L66

**Comment by sualko** [comment]
Mh, I only get and see on Travis the last two errors, but anyway I don't want to release different versions for different nc versions, because then the version would not align with the jsxc release.

I think it's ok if we ignore them and the other stuff should be updated in a new pr. Do you have an idea how we still could satisfy travis?

**Comment by sualko** [comment]
Do you have an idea how to fix travis? I tried to remove the composer.lock file in 349f2b4276bc5c0ac5528311c2f986c0bfb35bf6, but this just gave some other errors.

**Comment by LEDfan** [comment]
Let's see if this works :see_no_evil: ....

**Comment by LEDfan** [comment]
Builds are finally working!

**Comment by sualko** [comment]
:tada: great work

**Pull request merged**
