### PR TITLE
Support @ in usernames

### LINKED ISSUE #59: Chat does not work when username contains '@'
Steps to reproduce

Create users:
Create two users accounts with username contains '@' like abc@test.com and cde@test.com

Enable JavaScript XMPP Chat (v 3.2.1)

Configure JavaScript Xmpp Client as Internal

Login with: abc@test.com and cde@test.com, start a chat and send a messages between this accounts

Expected behaviour

Messages sent from abc@test.com to cde@test.com are sent successfully

Actual behaviour

Messages sent from abc@test.com to cde@test.com do not arrive

Server configuration

Operating system: Ubuntu 16.04
Nextcloud version: 12.0.2
Database: Postgresql 9.6
Web server: Nginx
PHP version: 7.0

### PR DESCRIPTION
**Pull request by LEDfan**
Fixes #59 

Test build:
[ojsxc-3.3.0-beta.1.tar.gz](https://github.com/nextcloud/jsxc.nextcloud/files/1247884/ojsxc-3.3.0-beta.1.tar.gz)

### CODE REVIEW

**Comment by alxarce** [comment]
When will a release with this fix published?

**Comment by MarcelWaldvogel** [comment]
@LEDfan What do you think?

**Comment by LEDfan** [comment]
@MarcelWaldvogel for me this can be released, but normally @sualko uploads to the Appstore, I don't have access to it.

**Comment by sualko** [comment]
> When will a release with this fix published?

Probably next week.

**Comment by alxarce** [comment]
i will wait for the release update

**Pull request merged**
