### PR TITLE
Don't include the resource inside the jid of roster pushes, since thi…

### PR DESCRIPTION
**Pull request by LEDfan**
…s is needed by XMPP spec (https://github.com/jsxc/jsxc/commit/3aa3f9dd987b5903f56120155dd2ad5e382182f1)

Fixes jsxc/jsxc#625

### CODE REVIEW

**Comment by LEDfan** [comment]
Build: [ojsxc-fix_625.tar.gz](https://github.com/nextcloud/jsxc.nextcloud/files/1346443/ojsxc-fix_625.tar.gz)

**Comment by sualko** [comment]
> There was 1 failure:
> 1) OCA\OJSXC\StanzaHandlers\IQTest::testIqRoster with data set #1 (array('{jabber:client}iq', array(array('{jabber:iq:roster}query', null, array())), array('get', 'f9a26583-3c59-4f09-89be-964ce...sendIQ')), array(Mock_IUser_770437b7 Object (...), Mock_IUser_770437b7 Object (...)), PHPUnit_Framework_MockObject_Matcher_InvokedCount Object (...), OCA\OJSXC\Db\IQRoster Object (...))
null does not match expected type "array".
/home/travis/build/nextcloud/nextcloud/apps/ojsxc/tests/unit/stanzahandlers/IQTest.php:169

**Comment by LEDfan** [comment]
Offending characters in the Nextcloud userid will now be escaped.
[ojsxc-fix_625.tar.gz](https://github.com/nextcloud/jsxc.nextcloud/files/1385227/ojsxc-fix_625.tar.gz)

**Comment by sualko** [comment]
Can this be merged? I would like to release a new version asap. Btw thanks for your amazing work :+1:

**Pull request merged**
