### PR TITLE
Update roster when creating, deleting and changing users

### PR DESCRIPTION
**Pull request by LEDfan**
This updates the roster of all clients when a user is created, deleted or updated.

Fixes https://github.com/jsxc/jsxc/issues/565

### CODE REVIEW

**Comment by LEDfan** [comment]
This also fixes an avatar loading issue.

**Comment by LEDfan** [comment]
TODO: 
 - [ ] also send a stanza to remove deleted uses (using the `addressbookchanges` table) 
 - [ ] execute the refresh on app install/enable using `install.php`

**Comment by LEDfan** [comment]
The filenames must be in lowercase to support Nextcloud 9 (I think it works in >9 because of some PSR4 implementing in core), but indeed the classes should be CamelCase. Sometimes an IDE does too much, thanks for catching 👍

**Comment by LEDfan** [comment]
[ojsxc-3.2.1.tar.gz](https://github.com/nextcloud/jsxc.nextcloud/files/1150174/ojsxc-3.2.1.tar.gz)

**Comment by sualko** [comment]
I can confirm the message delivery bug and also that the fix is working. :+1: Good job @LEDfan  and great catch @Schmuuu.

**Comment by Schmuuu** [comment]
Hi @sualko 

Thanks a lot! I'm very glad I could help somehow. 
I can also confirm the fix is working. Great Job @LEDfan !

**Comment by sualko** [comment]
@LEDfan I would like to make a new (beta) release in the next few days. Do you think we can merge or do you need more time?

**Comment by LEDfan** [comment]
@sualko it's okay for me to merge this, I'll do the TODO's in a follow-up PR then (they are only some race conditions)

**Comment by sualko** [comment]
@LEDfan do they need to go into the beta release?

**Comment by LEDfan** [comment]
@sualko I'll probably work on it tomorrow or Saturday, but I don't think they need to go into the beta.

**Comment by Nils160988** [comment]
I am not sure if I have to create a new issue or post it somewhere else, but there seems to be a regression after the update of the app to version 3.3.0.

After the update to 3.3.0 the old problems showed up again.
Everything seems to work with the zip provided here after manual downgrading.

**Comment by sualko** [comment]
@Nils160988 please open an new issue, so we can keep track of it.

**Pull request merged**
