### PR TITLE
Travis PHP 7.3 test

### PR DESCRIPTION
**Pull request by xf-**

### CODE REVIEW

**Comment by xf-** [comment]
Fails on friendsofphp/php-cs-fixer
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3697

**Comment by sualko** [comment]
Thanks for your PR. I see no emerging need to currently test php 7.3 and therefore we will wait to merge this, until the php-cs-fixer ist fixed. Maybe you can remind me if it's done.

**Comment by sualko** [comment]
Why did you close this pr?

**Comment by xf-** [comment]
@suntala i don't use jsxc anymore. Rebase didn't help with 7.3 support (^2.10 includes a 7.3 support release). I'm not planning to fix/investigate the issue.
i will reopen the PR and you can edit it.

**Pull request merged**
