### PR TITLE
Ejabberd cloud auth

### PR DESCRIPTION
**Pull request by sualko**
Endpoint for https://github.com/jsxc/ejabberd-cloud-auth

### CODE REVIEW

**Comment by sualko** [comment]
@fancycode @rossdraper @bigbigQI @jybeeL @wargreen @ctillmann

This new ejabberd authentication script needs some testing. Just update your ojsxc installation according to this PR and setup the script as described in the [corresponding repository](https://github.com/jsxc/ejabberd-cloud-auth) (watch for :warning:).

Any feedback will be appreciated.

**Comment by sualko** [comment]
@LukasReschke any security concerns?

**Comment by fsedarkalex** [comment]
This will only work for ejabberd right? Asking because of link in  jsxc/jsxc#489

**Comment by sualko** [comment]
No, I extended the script so that it also works for prosody. Please check 
the corresponding repo.


Am 15. März 2017 6:10:34 nachm. schrieb fsedarkalex <notifications@github.com>:

**Pull request merged**
